- CHANGELOG.md
- src/al/alAddVarCodeCommand.ts
- src/al/alCodeCommand.ts
- src/al/alFileCrawler.ts
- src/al/alFiles.ts
- src/al/alVarHelper.ts
> Change variable name to recommended var name

- CHANGELOG.md
- package.json
- src/additional/fileJumper.ts
- src/al/alAddVarCodeCommand.ts
- src/al/alFileCrawler.ts
- src/extension.ts
> Jump to next DateItem starting from bottom of file

- CHANGELOG.md
- package.json
- src/al/alAddVarCodeCommand.ts
- src/al/alFiles.ts
> Support for test libraries

- CHANGELOG.md
- src/additional/commandType.ts
- src/additional/objectTypes.ts
- src/additional/textBuilder.ts
- src/al/alAddVarOrParamCodeCommand.ts
- src/al/alCodeActionsProvider.ts
- src/al/alCodeCommand.ts
- src/al/alDataType.ts
- src/al/alFileCrawler.ts
- src/al/alFiles.ts
- src/al/alVariable.ts
> Add Parameter

- CHANGELOG.md
- package.json
- src/al/alFiles.ts
> Track changed file names and object names correctly

- src/al/alFileCrawler.ts
> Do not show "Add variable local" or "Add parameter" if user is using CodeAction in Request Page

- CHANGELOG.md
- package.json
- src/additional/textBuilder.ts
- src/al/alFiles.ts
> Fix indentation when creating variable block with CodeAction

- CHANGELOG.md
- package.json
- src/additional/textBuilder.ts
- src/al/alCodeActionsProvider.ts
- src/al/alFiles.ts
- src/al/reportCreator.ts
- src/extension.ts
> New Feature: Copy Report Layout (Export Layout from Base App Symbol)

- CHANGELOG.md
- package.json
- src/additional/devToolsExtensionContext.ts
- src/al/alAddVarOrParamCodeCommand.ts
- src/al/alFiles.ts
> Enums are not shown for some reason

- CHANGELOG.md
- README.md
- package.json
- src/additional/translationService.ts
> Translation not found

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/additional/textBuilder.ts
> Indentation for created variable section is wrong

- CHANGELOG.md
- package-lock.json
- package.json
- src/additional/diagnosticAnalyzer.ts
- src/al/alCodeActionsProvider.ts
- src/al/alFiles.ts
- src/extension.ts
- tsconfig.json
- tslint.json
> CodeActions not appearing

- CHANGELOG.md
- package-lock.json
- package.json
- src/additional/stringFunctions.ts
- src/additional/translationService.ts
> Special characters in Spanish

- CHANGELOG.md
- package.json
- src/al/alFileCrawler.ts
> Bug: Add variable

- .github/workflows/PublishExtension.yaml
> use publish vs code extension

- CHANGELOG.md
- package.json
- src/additional/fieldHover.ts
- src/extension.ts
- src/translation/translationService.ts
- src/translation/translator.ts
> Copy Translation to Clipboard, Translate Tooltipps

- CHANGELOG.md
- package.json
- src/al_code_outline/devToolsExtensionContext.ts
> Create report functionality does not find reports

- CHANGELOG.md
- package.json
- src/al_code_outline/devToolsExtensionContext.ts
> Add local/global variable throws an error

- CHANGELOG.md
- package-lock.json
- package.json
- src/al/report/report.ts
- src/files/fileHelper.ts
> Create a new report copies wrong report

- CHANGELOG.md
- package.json
- src/translation/translator.ts
> Show Translation and copy to clipboard improvment

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/json/launchjson_updater.ts
> Change launch.json startup object id by drop down list

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/al/codeActions/reportRenameProvider.ts
- src/al/report/variableSync.ts
- src/extension.ts
- src/translation/translationService.ts
> Implement renaming functionality for report dataset columns that also updates rdl

- CHANGELOG.md
- package.json
- src/files/folderHelper.ts
> Cannot find .alpackages folder when shared via al.packageCachePath
